### ISSUE TITLE
Error on DirectML, double and float on c_device and d_type

### ISSUE THREAD

**Issue by MythicalChu** [wootwootwootwoot/ComfyUI-RK-Sampler#2]
c_dtype = torch.float64 in nodes_rk_sampler.py in the default of _call_torchode and _call_scipy leads to an error on denoised[~mask] = denoised_model.to(self.c_device, dtype=self.c_dtype) in torchode_ode_term.py, self.c_device is a double and self.c_dtype is a float. I assume this only happens on DirectML, as so many of other headache inducing details... But MPS might be effected by it too.

I changed those to torch.float32 and it works normally (although I have no idea if that has an effect on the results).

**Comment by memmaptensor** [comment]
https://github.com/wootwootwootwoot/ComfyUI-RK-Sampler/commit/d03c40d74f2ba87273c64d905b31d135d87c2694 should fix it.

Let me know if it still doesn't work.
